"""
Django settings for koyra_web project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

import dj_database_url
from django.templatetags.static import static
from django.urls import reverse_lazy
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charge un fichier .env local s'il existe (ignoré en production).
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-joyi=7i&q)@cn^f2ne(@hp-ern9+nqy%z#fyta3x3^a69oo0(n',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

# Render fournit ce hostname automatiquement.
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalogue',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'koyra_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'koyra_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# En production, Render fournit DATABASE_URL. En local, on retombe sur la
# base PostgreSQL locale (mot de passe via la variable DB_PASSWORD).
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv(
            'DATABASE_URL',
            'postgres://postgres:{pwd}@localhost:5432/koyra_db'.format(
                pwd=os.getenv('DB_PASSWORD', ''),
            ),
        ),
        conn_max_age=600,
        ssl_require=env_bool('DB_SSL_REQUIRE', False),
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# WhiteNoise : compression + noms de fichiers versionnés en production.
# En dev (DEBUG), on garde le stockage simple pour ne pas exiger un collectstatic.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

MEDIA_URL = '/media/'
# En local : dossier BASE_DIR/media. Sur un plan payant : disque persistant.
MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# --- Stockage des images produits ------------------------------------
# Sur l'offre gratuite de Render le disque est éphémère : sans stockage
# externe (ou disque payant) les images téléversées finissent par
# disparaître. Priorité : Firebase/GCS -> S3 -> Cloudinary -> disque local.
GS_BUCKET_NAME = os.getenv('GS_BUCKET_NAME', '')          # <projet>.firebasestorage.app
S3_ENDPOINT_URL = os.getenv('S3_ENDPOINT_URL', '')
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL', '')

# 1) Firebase Storage (= bucket Google Cloud Storage)
if GS_BUCKET_NAME:
    import json as _json
    from google.oauth2 import service_account as _sa

    _raw = os.getenv('GS_CREDENTIALS_JSON', '')
    try:
        _info = _json.loads(_raw)
    except _json.JSONDecodeError:
        import base64 as _b64
        _info = _json.loads(_b64.b64decode(_raw))

    from datetime import timedelta as _td

    INSTALLED_APPS += ['storages']
    STORAGES['default'] = {'BACKEND': 'storages.backends.gcloud.GoogleCloudStorage'}
    GS_CREDENTIALS = _sa.Credentials.from_service_account_info(_info)
    GS_PROJECT_ID = _info.get('project_id')
    GS_DEFAULT_ACL = None
    # Le bucket reste privé : on sert des URLs signées (aucun réglage de
    # permission à faire côté Firebase). Régénérées à chaque rendu de page.
    GS_QUERYSTRING_AUTH = True
    GS_EXPIRATION = _td(hours=24)
    GS_FILE_OVERWRITE = False
    GS_LOCATION = 'media'

# 2) S3 / compatible S3 (Backblaze B2, Cloudflare R2, Wasabi, MinIO, AWS…)
elif S3_ENDPOINT_URL:
    INSTALLED_APPS += ['storages']
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}
    AWS_S3_ENDPOINT_URL = S3_ENDPOINT_URL
    AWS_ACCESS_KEY_ID = os.getenv('S3_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.getenv('S3_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.getenv('S3_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.getenv('S3_REGION', '') or None
    AWS_S3_ADDRESSING_STYLE = os.getenv('S3_ADDRESSING_STYLE', 'virtual')
    AWS_S3_CUSTOM_DOMAIN = os.getenv('S3_CUSTOM_DOMAIN', '') or None
    # Bucket privé par défaut -> URLs signées (les buckets publics sont
    # souvent payants). Mettre S3_SIGNED=false si le bucket est public.
    AWS_QUERYSTRING_AUTH = env_bool('S3_SIGNED', True)
    AWS_QUERYSTRING_EXPIRE = int(os.getenv('S3_URL_EXPIRE', '86400'))  # 24 h
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_LOCATION = 'media'

# 3) Cloudinary  (format : cloudinary://<api_key>:<api_secret>@<cloud_name>)
elif CLOUDINARY_URL:
    INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']
    STORAGES['default'] = {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    }


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Sans configuration SMTP, les e-mails s'affichent dans la console (dev).
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = env_bool('EMAIL_USE_SSL', False)
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL', 'Koyra Distribution <no-reply@koyradistribution.com>'
)
# Adresse qui reçoit les messages du formulaire de contact.
CONTACT_NOTIFICATION_EMAIL = os.getenv(
    'CONTACT_NOTIFICATION_EMAIL', 'contact@koyradistribution.com'
)

# Jeton de la page d'installation /installation/<jeton>/ : elle n'est active
# que si ce jeton est défini ET qu'aucun super-utilisateur n'existe encore.
# Vide (défaut) => page désactivée (404).
ADMIN_SETUP_TOKEN = os.getenv('ADMIN_SETUP_TOKEN', '')

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '2592000'))  # 30 j
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

# -----------------------------------------------------------------------------
# Django Unfold - interface d'administration premium
# https://unfoldadmin.com/docs/
# -----------------------------------------------------------------------------
UNFOLD = {
    "SITE_TITLE": "Administration Koyra",
    "SITE_HEADER": "Koyra Distribution",
    "SITE_SUBHEADER": "Espace de gestion",
    "SITE_URL": "/",
    "SITE_SYMBOL": "eco",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": None,  # laisse l'utilisateur choisir clair / sombre
    "BORDER_RADIUS": "8px",
    "DASHBOARD_CALLBACK": "catalogue.dashboard.dashboard_callback",
    "STYLES": [
        lambda request: static("admin/css/koyra-unfold.css"),
    ],
    "LOGIN": {
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },
    "COLORS": {
        "base": {
            "50": "252 250 246",
            "100": "247 243 236",
            "200": "237 243 236",
            "300": "214 209 199",
            "400": "161 156 145",
            "500": "115 110 99",
            "600": "82 78 69",
            "700": "63 60 52",
            "800": "41 39 34",
            "900": "26 25 22",
            "950": "17 16 14",
        },
        "primary": {
            "50": "243 247 242",
            "100": "226 236 224",
            "200": "198 218 193",
            "300": "157 191 149",
            "400": "109 156 98",
            "500": "74 125 63",
            "600": "55 99 47",
            "700": "46 90 39",
            "800": "36 74 32",
            "900": "28 58 26",
            "950": "21 50 21",
        },
        "font": {
            "subtle-light": "115 110 99",
            "subtle-dark": "161 156 145",
            "default-light": "63 60 52",
            "default-dark": "237 243 236",
            "important-light": "26 25 22",
            "important-dark": "252 250 246",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Catalogue",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Tableau de bord",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Marques",
                        "icon": "storefront",
                        "link": reverse_lazy("admin:catalogue_marque_changelist"),
                    },
                    {
                        "title": "Catégories",
                        "icon": "category",
                        "link": reverse_lazy("admin:catalogue_categorie_changelist"),
                    },
                    {
                        "title": "Produits",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:catalogue_produit_changelist"),
                    },
                ],
            },
            {
                "title": "Relation client",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Messages de contact",
                        "icon": "mail",
                        "link": reverse_lazy("admin:catalogue_messagecontact_changelist"),
                        "badge": "catalogue.dashboard.badge_messages_non_traites",
                    },
                ],
            },
            {
                "title": "Administration",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Utilisateurs",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groupes",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
