"""
Django settings for koyra_web project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os

from django.templatetags.static import static
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-joyi=7i&q)@cn^f2ne(@hp-ern9+nqy%z#fyta3x3^a69oo0(n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'catalogue',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'koyra_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'koyra_web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'koyra_db',
        'USER': 'postgres',
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# -----------------------------------------------------------------------------
# Django Unfold - interface d'administration premium
# https://unfoldadmin.com/docs/
# -----------------------------------------------------------------------------
UNFOLD = {
    "SITE_TITLE": "Administration Koyra",
    "SITE_HEADER": "Koyra Distribution",
    "SITE_SUBHEADER": "Espace de gestion",
    "SITE_URL": "/",
    "SITE_SYMBOL": "eco",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": None,  # laisse l'utilisateur choisir clair / sombre
    "BORDER_RADIUS": "8px",
    "DASHBOARD_CALLBACK": "catalogue.dashboard.dashboard_callback",
    "STYLES": [
        lambda request: static("admin/css/koyra-unfold.css"),
    ],
    "LOGIN": {
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },
    "COLORS": {
        "base": {
            "50": "252 250 246",
            "100": "247 243 236",
            "200": "237 243 236",
            "300": "214 209 199",
            "400": "161 156 145",
            "500": "115 110 99",
            "600": "82 78 69",
            "700": "63 60 52",
            "800": "41 39 34",
            "900": "26 25 22",
            "950": "17 16 14",
        },
        "primary": {
            "50": "243 247 242",
            "100": "226 236 224",
            "200": "198 218 193",
            "300": "157 191 149",
            "400": "109 156 98",
            "500": "74 125 63",
            "600": "55 99 47",
            "700": "46 90 39",
            "800": "36 74 32",
            "900": "28 58 26",
            "950": "21 50 21",
        },
        "font": {
            "subtle-light": "115 110 99",
            "subtle-dark": "161 156 145",
            "default-light": "63 60 52",
            "default-dark": "237 243 236",
            "important-light": "26 25 22",
            "important-dark": "252 250 246",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Catalogue",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Tableau de bord",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Marques",
                        "icon": "storefront",
                        "link": reverse_lazy("admin:catalogue_marque_changelist"),
                    },
                    {
                        "title": "Catégories",
                        "icon": "category",
                        "link": reverse_lazy("admin:catalogue_categorie_changelist"),
                    },
                    {
                        "title": "Produits",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:catalogue_produit_changelist"),
                    },
                ],
            },
            {
                "title": "Relation client",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Messages de contact",
                        "icon": "mail",
                        "link": reverse_lazy("admin:catalogue_messagecontact_changelist"),
                        "badge": "catalogue.dashboard.badge_messages_non_traites",
                    },
                ],
            },
            {
                "title": "Administration",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Utilisateurs",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Groupes",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}
